all: main.cpp aleatorios.cpp element.cpp funciones.cpp gestionarFile.cpp point.cpp
	g++ -std=c++14 main.cpp aleatorios.cpp element.cpp funciones.cpp gestionarFile.cpp point.cpp -o main

clean:
	rm main
