# Generated by Django 3.0.4 on 2020-07-18 10:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_voltajes', models.IntegerField()),
                ('n_impedancias', models.IntegerField()),
                ('linea_inicio_vol', models.IntegerField()),
                ('linea_fin_vol', models.IntegerField()),
                ('linea_inicio_imp', models.IntegerField()),
                ('linea_fin_imp', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('normalizado', models.BooleanField()),
                ('numero_electrodos', models.IntegerField()),
                ('patron_estimulacion', models.CharField(max_length=30)),
                ('r_min', models.IntegerField()),
                ('r_max', models.IntegerField()),
                ('semilla', models.IntegerField()),
                ('visible', models.BooleanField()),
                ('estado', models.CharField(max_length=100, null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.IntegerField()),
                ('numero_artefactos', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomo.Dataset')),
            ],
            options={
                'unique_together': {('indice', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('comentarios_adicionales', models.CharField(max_length=300)),
                ('visible', models.BooleanField()),
                ('estado', models.CharField(max_length=50, null=True)),
                ('binario_modelo', models.BinaryField(null=True)),
                ('path_modelo', models.CharField(max_length=300, null=True)),
                ('umbral_postprocesado', models.FloatField(null=True)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tomo.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Conjunto_impedancias',
            fields=[
                ('id_malla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tomo.Malla')),
                ('impedancias', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Conjunto_voltajes',
            fields=[
                ('id_malla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tomo.Malla')),
                ('voltajes', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz_confusion',
            fields=[
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tomo.Modelo')),
                ('verdaderos_negativos', models.IntegerField()),
                ('falsos_positivos', models.IntegerField()),
                ('falsos_negativos', models.IntegerField()),
                ('verdaderos_positivos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_maquina_soporte_vectorial',
            fields=[
                ('id_modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tomo.Modelo')),
                ('kernel', models.CharField(max_length=30)),
                ('grado', models.IntegerField()),
                ('gamma', models.CharField(max_length=30)),
                ('coef0', models.FloatField()),
                ('tol', models.FloatField()),
                ('c', models.FloatField()),
                ('epsilon', models.FloatField()),
                ('binario_modelo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_random_forest',
            fields=[
                ('id_modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tomo.Modelo')),
                ('n_estimadores', models.IntegerField()),
                ('profundidad_max', models.IntegerField()),
                ('min_samples_split', models.IntegerField()),
                ('min_samples_leaf', models.IntegerField()),
                ('binario_modelo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_red_neuronal',
            fields=[
                ('id_modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tomo.Modelo')),
                ('capas_ocultas', models.IntegerField()),
                ('neuronas_por_capa', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=10)),
                ('funcion_activacion_interna', models.CharField(max_length=30)),
                ('funcion_activacion_salida', models.CharField(max_length=30)),
                ('funcion_error', models.CharField(max_length=30)),
                ('epocas', models.IntegerField()),
                ('lotes', models.IntegerField(null=True)),
                ('learning_rate', models.FloatField()),
                ('momentum', models.FloatField()),
                ('binario_arquitectura', models.BinaryField()),
                ('binario_pesos', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metrica', models.CharField(max_length=100)),
                ('valor_metrica', models.FloatField(null=True)),
                ('id_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomo.Modelo')),
            ],
        ),
    ]
