# Generated by Django 3.0.4 on 2021-11-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0002_remove_dataset_datetime_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='datetime_start',
            new_name='creation_date',
        ),
    ]
