# Generated by Django 3.0.4 on 2021-11-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0002_auto_20211110_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='comentaries',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='path_model',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
