# Generated by Django 3.0.4 on 2020-07-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0003_imagenreconstruida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenReconstruida',
        ),
    ]
