# Generated by Django 3.0.4 on 2020-08-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0005_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
