# Generated by Django 3.0.4 on 2020-08-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0007_remove_dataset_normalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='malla',
            options={'ordering': ('indice',)},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='malla',
            old_name='impedancias',
            new_name='conductividades',
        ),
    ]
