# Generated by Django 3.0.4 on 2020-08-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0008_auto_20200826_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='binario_modelo',
        ),
    ]
