# Generated by Django 3.0.4 on 2020-08-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0009_remove_modelo_binario_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='numero_electrodos',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='patron_estimulacion',
        ),
    ]
