# Generated by Django 3.0.4 on 2020-10-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomo', '0010_auto_20200828_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
